server:
  port: ${GATEWAY_PORT:80}

spring:
  application:
    name: ${GATEWAY_NAME:gateway}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            - allowedOrigins: ["localhost:4200"]
            - allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      routes:
        - id: zipkin
          uri: http://${LOCALHOST:zipkin}:9411
          predicates:
            - Path=/zipkin/**
        - id: discovery
          uri: http://${LOCALHOST:discovery}:${DISCOVERY_PORT:8088}
          predicates:
            - Path=/discovery/**
          filters:
            - RewritePath=/discovery/(?<path>.*), /$\{path}
            - RewritePath=/discovery, /
        - id: eureka
          uri: http://${LOCALHOST:discovery}:${DISCOVERY_PORT:8088}
          predicates:
            - Path=/eureka/**
        - id: broker
          uri: http://rabbitmq:${RABBITMQ_PORT:15672}
          predicates:
            - Path=/broker/**
          filters:
            - RewritePath=/broker/(?<path>.*), /$\{path}
            - RewritePath=/broker, /
        - id: accounts
          uri: lb://bank-accounts
          predicates:
            - Path=/accounts/**
        - id: transfers
          uri: lb://bank-transfers
          predicates:
            - Path=/transfers/**
          #filters:
          #  - RewritePath=/transfers/(?<path>.*), /$\{path}
        - id: webapp
          uri: http://webapp:80
          predicates:
            - Path=/**
          filters:
            - RewritePath=/webapp/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${LOCALHOST:discovery}:${DISCOVERY_PORT:8088}/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG